#!/bin/sh

# Cleanup previous builds and traces
rm -rf obj_dir
rm -f sigdelay.vcd
rm -f sigdelay.mem

# Run Python script to generate sine ROM data
python3 sinegen.py

# Run Verilator to translate Verilog into C++, including the C++ testbench
verilator -Wall --cc --trace sigdelay.sv ram.sv counter.sv --exe sigdelay_tb.cpp

# Build the C++ project via the makefile automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# Run the executable simulation file
./obj_dir/Vsigdelay
