#!/bin/sh

# Cleanup previous builds and traces
rm -rf obj_dir
rm -f sinegen.vcd
rm -f sinerom.mem

# Run Python script to generate sine ROM data
python3 sinegen.py

# Run Verilator to translate Verilog into C++, including the C++ testbench
verilator -Wall --cc --trace sinegen.sv rom.sv counter.sv --exe sinegen_tb.cpp

# Build the C++ project via the makefile automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# Run the executable simulation file
./obj_dir/Vsinegen
